name: Java
on:
  push:   
  workflow_dispatch:

jobs:
  hello-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
    - name: list
      run: |
        ls
        pwd
    - name: Setup Java JDK
      uses: actions/setup-java@v2
    - name: Compile and Run Java
      run: |
        javac hello.java
        java hello

      
