name: Java
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:

jobs:
  hello-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
    - name: list
      run: |
        ls
        pwd

    - name: Setup Java JDK
      uses: oracle-actions/setup-java@v1.3.1

    - name: Compile and Run Java
      run: |
        javac hello.java
        java hello
