name: Run Java Program
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-java:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Distribution type
        java-version: '11'     # Adjust the Java version as needed
        
    - name: Compile and Run Java
      run: |
        javac hello.java
        java hello
