name: hello-world
on:
  push:
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: running echo command
      run:
        pwd
        touch test.txt
        ls
        
        pwd
      shell: bash
    
  
