name: hello-world
on:
  push:
  workflow_dispatch:
jobs:
  Jenkins_install:
    runs-on: ubuntu-latest
    steps:
    - name: Import Jenkins GPG key
      run: |
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
        
    - name: Adding repositories
      run: |
        sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      
    - name: Update package lists
      run: |
        sudo apt update
        
    - name: installing Jenkins
      run: |
        sudo apt install jenkins
